### ISSUE TITLE
Needs more swag

### ISSUE THREAD

**Issue by zayKenyon** [OwOHamper/OwOHamper#1]
![baker-job-description-6000x4000-20201123.jpeg](https://user-images.githubusercontent.com/87788699/128387719-a4482032-d23b-4abd-b498-d0cae8117629.jpeg)

**Comment by teoobarca** [comment]
![image](https://user-images.githubusercontent.com/74879467/128411658-098290d4-647e-485a-9f70-e3678caff515.png)
